### ISSUE TITLE
Inappropriate warning from defvocab

### ISSUE THREAD

**Issue by ijdickinson** [rdf-elixir/rdf-ex#15]
I'm getting some warnings when I load a vocabulary using `defvocab` that, to me, don't look correct.

Here's the vocabulary:

```turtle
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix owl: <http://www.w3.org/2002/07/owl#>.

@prefix habitat: <http://verna.earth/def/core/habitat/> .

#######################
# Conditions
#######################

habitat:Condition
  a owl:Class ;
  rdfs:comment "Denotes the class of condition categories for habitats" ;
  skos:prefLabel "condition" .

habitat:conditionScore
  a owl:DataTypeProperty ;
  rdfs:comment "Denotes the multiplier for condition used in BNG calculations"@en ;
  skos:prefLabel "condition score"@en ;
  rdfs:domain habitat:Condition ;
  rdfs:range xsd:float .

# instance data below originally extracted from BNG Metric 3.1

habitat:conditionAssessmentNA
  a habitat:Condition ;
  habitat:conditionScore "1.0"^^xsd:float ;
  skos:prefLabel "Condition Assessment N/A"@en .

habitat:conditions
  a skos:ConceptScheme ;
  skos:prefLabel "A concept scheme for BNG Metric 3.1 condition categories."@en ;
  skos:hasTopConcept habitat:conditionAssessmentNA ;
  skos:hasTopConcept habitat:fairlyGood ;
  skos:hasTopConcept habitat:fairlyPoor ;
  skos:hasTopConcept habitat:good ;
  skos:hasTopConcept habitat:moderate ;
  skos:hasTopConcept habitat:nAOther ;
  skos:hasTopConcept habitat:poor .

habitat:fairlyGood
  a habitat:Condition ;
  habitat:conditionScore "2.5"^^xsd:float ;
  skos:prefLabel "Fairly Good"@en .

habitat:fairlyPoor
  a habitat:Condition ;
  habitat:conditionScore "1.5"^^xsd:float ;
  skos:prefLabel "Fairly Poor"@en .

habitat:good
  a habitat:Condition ;
  habitat:conditionScore "3.0"^^xsd:float ;
  skos:prefLabel "Good"@en .

habitat:moderate
  a habitat:Condition ;
  habitat:conditionScore "2.0"^^xsd:float ;
  skos:prefLabel "Moderate"@en .

habitat:nAOther
  a habitat:Condition ;
  habitat:conditionScore "0.0"^^xsd:float ;
  skos:prefLabel "N/A - Other"@en .

habitat:poor
  a habitat:Condition ;
  habitat:conditionScore "1.0"^^xsd:float ;
  skos:prefLabel "Poor"@en .
```

and here's the output I'm getting:

```text
ian@alder $ iex -S mix
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]
Interactive Elixir (1.13.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule NsTest do
...(1)> use RDF.Vocabulary.Namespace
...(1)> defvocab Condition,
...(1)>     base_iri: "http://verna.earth/def/core/habitat/",
...(1)>     file: "condition.ttl"
...(1)> end
Compiling vocabulary namespace for http://verna.earth/def/core/habitat/
warning: 'http://verna.earth/def/core/habitat/conditionAssessmentNA' is a lowercased non-property resource
  (rdf 0.12.0) lib/rdf/vocabulary_namespace.ex:596: anonymous fn/4 in RDF.Vocabulary.Namespace.handle_case_violations/5
  (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
  (stdlib 4.0.1) maps.erl:411: :maps.fold_1/3
  (rdf 0.12.0) lib/rdf/vocabulary_namespace.ex:594: RDF.Vocabulary.Namespace.handle_case_violations/5
  (rdf 0.12.0) lib/rdf/vocabulary_namespace.ex:55: RDF.Vocabulary.Namespace."MACRO-defvocab"/3
  (elixir 1.13.4) src/elixir_dispatch.erl:202: :elixir_dispatch.expand_macro_fun/7
  (elixir 1.13.4) src/elixir_dispatch.erl:165: :elixir_dispatch.do_expand_import/7
  (elixir 1.13.4) src/elixir_dispatch.erl:92: :elixir_dispatch.dispatch_import/6
  (elixir 1.13.4) src/elixir_expand.erl:547: :elixir_expand.expand_block/5
  (elixir 1.13.4) src/elixir_expand.erl:40: :elixir_expand.expand/3
  (elixir 1.13.4) src/elixir_expand.erl:10: :elixir_expand.expand/3
  (elixir 1.13.4) src/elixir_expand.erl:550: :elixir_expand.expand_block/5
  (elixir 1.13.4) src/elixir_expand.erl:40: :elixir_expand.expand/3
  (elixir 1.13.4) src/elixir_compiler.erl:51: :elixir_compiler.compile/3
  (elixir 1.13.4) src/elixir_module.erl:369: :elixir_module.eval_form/6
  (elixir 1.13.4) src/elixir_module.erl:105: :elixir_module.compile/5
  (elixir 1.13.4) src/elixir_lexical.erl:15: :elixir_lexical.run/3
  (stdlib 4.0.1) erl_eval.erl:744: :erl_eval.do_apply/7

warning: 'http://verna.earth/def/core/habitat/conditions' is a lowercased non-property resource
  (rdf 0.12.0) lib/rdf/vocabulary_namespace.ex:596: anonymous fn/4 in RDF.Vocabulary.Namespace.handle_case_violations/5
  (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
  (stdlib 4.0.1) maps.erl:411: :maps.fold_1/3
  (rdf 0.12.0) lib/rdf/vocabulary_namespace.ex:594: RDF.Vocabulary.Namespace.handle_case_violations/5
  (rdf 0.12.0) lib/rdf/vocabulary_namespace.ex:55: RDF.Vocabulary.Namespace."MACRO-defvocab"/3
  (elixir 1.13.4) src/elixir_dispatch.erl:202: :elixir_dispatch.expand_macro_fun/7
  (elixir 1.13.4) src/elixir_dispatch.erl:165: :elixir_dispatch.do_expand_import/7
  (elixir 1.13.4) src/elixir_dispatch.erl:92: :elixir_dispatch.dispatch_import/6
  (elixir 1.13.4) src/elixir_expand.erl:547: :elixir_expand.expand_block/5
  (elixir 1.13.4) src/elixir_expand.erl:40: :elixir_expand.expand/3
  (elixir 1.13.4) src/elixir_expand.erl:10: :elixir_expand.expand/3
  (elixir 1.13.4) src/elixir_expand.erl:550: :elixir_expand.expand_block/5
  (elixir 1.13.4) src/elixir_expand.erl:40: :elixir_expand.expand/3
  (elixir 1.13.4) src/elixir_compiler.erl:51: :elixir_compiler.compile/3
  (elixir 1.13.4) src/elixir_module.erl:369: :elixir_module.eval_form/6
  (elixir 1.13.4) src/elixir_module.erl:105: :elixir_module.compile/5
  (elixir 1.13.4) src/elixir_lexical.erl:15: :elixir_lexical.run/3
  (stdlib 4.0.1) erl_eval.erl:744: :erl_eval.do_apply/7

warning: 'http://verna.earth/def/core/habitat/fairlyGood' is a lowercased non-property resource
  [ ... many more like this ...]

iex(2)>   
```

Why is being "a lowercased non-property resource" something that needs a warning? To my knowledge, using a lower-case localname for an instance of an `owl:Class` or `skos:Concept` is a standard practice.

**Comment by marcelotto** [comment]
Valid point. Will be removed in the next version.

**Comment by ijdickinson** [comment]
Great, thanks @marcelotto

**Comment by marcelotto** [comment]
My first answer was a bit short-handed because I didn’t had much time to go into the details. So, here’s the long answer now.

The warning isn’t actually inappropriate. You shouldn’t read these warnings of the compiler as complaints on some bad practice in your vocabulary. It warns about this, because the mapping to terms on Elixir modules you’ll get from this won’t be as intended. Lower-cased terms are assumed to be properties and mapped to functions, which can also be used to build statements with this property (see [https://rdf-elixir.dev/rdf-ex/description-and-graph-dsl.html#description-builder](https://rdf-elixir.dev/rdf-ex/description-and-graph-dsl.html#description-builder)). 

I think this assumption about the casing is still in accordance with most vocabularies which consist solely of classes and properties. But indeed there are vocabularies like yours who validly also contain instance data (not to mention the fact that nothing holds one back to define vocabulary namespace over pure instance data).

So, the proper way to get rid of this warning is to just define an upper-cased alias. But of course this isn’t practical when dealing with larger vocabularies. That's why I agree with your point.

In that case you now have two more options in RDF.ex 1.0:

- You can use the new  `allow_lowercase_resource_terms` option, which was added on `defvocab`. When set to `true`, the compliler no longer produces any complaints about such terms.
- You can set the newly supported `:auto_fix` value on the `case_violations` option of `defvocab`. Terms violating the casing assumptions are then aliased automatically to the expected casing.

BTW: In case you didn’t know, you can already set the `case_violations` option to `:ignore` with the current version to get rid of the warning.
